/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'createdAt' : Time,
  'text' : string,
  'author' : Principal,
  'videoId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Notification {
  'userId' : Principal,
  'createdAt' : Time,
  'isRead' : boolean,
  'message' : string,
}
export interface PartialUserProfile {
  'bio' : string,
  'username' : string,
  'avatarBlobKey' : [] | [ExternalBlob],
  'followerCount' : bigint,
  'followingCount' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : string,
  'title' : string,
  'creator' : Principal,
  'duration' : bigint,
  'reportCount' : bigint,
  'thumbnailKey' : ExternalBlob,
  'hashtags' : Array<string>,
  'blobKey' : ExternalBlob,
  'createdAt' : Time,
  'description' : string,
  'score' : bigint,
  'sharesCount' : bigint,
  'commentsCount' : bigint,
  'likesCount' : bigint,
  'musicName' : string,
  'savesCount' : bigint,
  'isRemoved' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, PartialUserProfile]>>,
  'getAnalytics' : ActorMethod<
    [],
    { 'totalReports' : bigint, 'totalVideos' : bigint, 'totalUsers' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], PartialUserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowingUsers' : ActorMethod<[Principal], Array<Principal>>,
  'getMyProfile' : ActorMethod<[], PartialUserProfile>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getProfile' : ActorMethod<[Principal], PartialUserProfile>,
  'getTrendingHashtags' : ActorMethod<[], Array<string>>,
  'getTrendingVideos' : ActorMethod<[], Array<Video>>,
  'getUserProfile' : ActorMethod<[Principal], PartialUserProfile>,
  'getUserVideos' : ActorMethod<[Principal], Array<Video>>,
  'getVideoComments' : ActorMethod<[string], Array<Comment>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'removeVideo' : ActorMethod<[string], undefined>,
  'reportVideo' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, [] | [ExternalBlob]],
    undefined
  >,
  'searchHashtags' : ActorMethod<[string], Array<string>>,
  'searchUsers' : ActorMethod<[string], Array<[Principal, PartialUserProfile]>>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'uploadVideo' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      ExternalBlob,
      ExternalBlob,
      string,
      bigint,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];