/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PartialUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarBlobKey' : IDL.Opt(ExternalBlob),
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'duration' : IDL.Nat,
  'reportCount' : IDL.Nat,
  'thumbnailKey' : ExternalBlob,
  'hashtags' : IDL.Vec(IDL.Text),
  'blobKey' : ExternalBlob,
  'createdAt' : Time,
  'description' : IDL.Text,
  'score' : IDL.Nat,
  'sharesCount' : IDL.Nat,
  'commentsCount' : IDL.Nat,
  'likesCount' : IDL.Nat,
  'musicName' : IDL.Text,
  'savesCount' : IDL.Nat,
  'isRemoved' : IDL.Bool,
});
export const Comment = IDL.Record({
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'videoId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PartialUserProfile))],
      ['query'],
    ),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalReports' : IDL.Nat,
          'totalVideos' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [PartialUserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowingUsers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [PartialUserProfile], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [PartialUserProfile], ['query']),
  'getTrendingHashtags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [PartialUserProfile], ['query']),
  'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'getVideoComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'removeVideo' : IDL.Func([IDL.Text], [], []),
  'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'searchHashtags' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PartialUserProfile))],
      ['query'],
    ),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        ExternalBlob,
        ExternalBlob,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PartialUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarBlobKey' : IDL.Opt(ExternalBlob),
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'duration' : IDL.Nat,
    'reportCount' : IDL.Nat,
    'thumbnailKey' : ExternalBlob,
    'hashtags' : IDL.Vec(IDL.Text),
    'blobKey' : ExternalBlob,
    'createdAt' : Time,
    'description' : IDL.Text,
    'score' : IDL.Nat,
    'sharesCount' : IDL.Nat,
    'commentsCount' : IDL.Nat,
    'likesCount' : IDL.Nat,
    'musicName' : IDL.Text,
    'savesCount' : IDL.Nat,
    'isRemoved' : IDL.Bool,
  });
  const Comment = IDL.Record({
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'videoId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PartialUserProfile))],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalReports' : IDL.Nat,
            'totalVideos' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [PartialUserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowingUsers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [PartialUserProfile], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [PartialUserProfile], ['query']),
    'getTrendingHashtags' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTrendingVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [PartialUserProfile],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
    'getVideoComments' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'removeVideo' : IDL.Func([IDL.Text], [], []),
    'reportVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'searchHashtags' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PartialUserProfile))],
        ['query'],
      ),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          ExternalBlob,
          ExternalBlob,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };